version: '3.7'

services:
  backend:
    image: nnikolovskii/dotnet_finki_rasporedi:latest
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=finki-rasporedi.c3ykc2um4mje.eu-central-1.rds.amazonaws.com;Port=3306;Database=finki_rasporedi;User=admin;Password=Ogan09875!;
    ports:
      - "7069:80"