name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image 1
      run: docker build ./docker/dockerfile1 --file ./docker/dockerfile1/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/rasporedi-backend:$(date +%s)

    - name: Build Docker image 2
      run: docker build ./docker/dockerfile2 --file ./docker/dockerfile2/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/rasporedi-frontend:$(date +%s)

    - name: Push Docker image 1
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rasporedi-backend:$(date +%s)

    - name: Push Docker image 2
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rasporedi-frontend:$(date +%s)
